20220216_180535 (update_mon)

diff --git a/functions/get_sudo b/functions/get_sudo
--- a/functions/get_sudo
+++ b/functions/get_sudo
@@ -3,36 +3,42 @@
 ##
 ### source function
 ###
-### 2019 -2022 (c) cytopyge
+### 2019 - 2022  |  cytopyge
 ##
 #
 
 
 get_sudo()
 {
-	## get sudo error status non interactive
-	sudo -n printf "" > /dev/null 2>&1
-
-	if [[ $? -ne 0 ]]; then
-
-		set -e
-
-		## reset cached credentials timestamp, always (re-)authenticate
-		#sudo -k
-
-		## validate; update cached credentials, authenticating only if necessary
-		## is always necessary in this if statement
-		echo
 		printf "${YELLOW}"
-		#printf "In order to obtain required privileges,\nplease enter ${YELLOW}"
 
 		sudo -v
 
 		printf "${NOC}"
 
-		set +e
+	## get sudo error status non interactive
+#	sudo -n printf "" > /dev/null 2>&1
+#
+#	if [[ $? -ne 0 ]]; then
+#
+#		set -e
+#
+#		## reset cached credentials timestamp, always (re-)authenticate
+#		#sudo -k
+#
+#		## validate; update cached credentials, authenticating only if necessary
+#		## is always necessary in this if statement
+#		echo
+#		printf "${YELLOW}"
+#		#printf "In order to obtain required privileges,\nplease enter ${YELLOW}"
+#
+#		sudo -v
+#
+#		printf "${NOC}"
+#
+#		set +e
+#
+#	fi
 
-	fi
-
-	echo
+#	echo
 }
