20210129_202804 (update_mon)

diff --git a/functions/get_sudo b/functions/get_sudo
--- a/functions/get_sudo
+++ b/functions/get_sudo
@@ -8,11 +8,26 @@
 
 get_sudo() {
 
-	set -e
-	sudo -k
-	printf "In order to obtain required privileges,\nplease enter ${YELLOW}"
-	sudo echo
-	printf "${NOC}"
-	set +e
+	## get sudo error status
+	sudo -n printf "" > /dev/null 2>&1
+
+	if [[ $? -ne 0 ]]; then
+
+		set -e
+
+		## reset cached credentials timestamp, always (re-)authenticate
+		#sudo -k
+
+		## validate; update cached credentials, authenticating only if necessary
+		## is always necessary in this if statement
+		printf "In order to obtain required privileges,\nplease enter ${YELLOW}"
+
+		sudo -v
+
+		printf "${NOC}"
+
+		set +e
+
+	fi
 
 }
